"""
Define common constants.
"""
from transformers import BertTokenizer


TRAIN_JSON = "train.json"
DEV_JSON = "dev.json"
TEST_JSON = "test.json"

GLOVE_DIR = "dataset/glove"
BERT_MODEL = "bert-base-cased"

EMB_INIT_RANGE = 1.0
MAX_LEN = 500

tokenizer = BertTokenizer.from_pretrained(BERT_MODEL)

# vocab
PAD_TOKEN = "[PAD]"
UNK_TOKEN = "[UNK]"
PAD_ID, UNK_ID = tokenizer.convert_tokens_to_ids([PAD_TOKEN, UNK_TOKEN])

VOCAB_PREFIX = [PAD_TOKEN, UNK_TOKEN]

# hard-coded mappings from fields to ids
SUBJ_NER_TO_ID = {
    PAD_TOKEN: PAD_ID,
    UNK_TOKEN: UNK_ID,
    # "ORGANIZATION": 2,
    # "PERSON": 3

    ## using subtype
    # "Medical-Science": 2,
    # "Airport": 3,
    # "Boundary": 4,
    # "Subarea-Facility": 5,
    # "Land-Region-Natural": 6,
    # "Path": 7,
    # "Plant": 8,
    # "Celestial": 9,
    # "Commercial": 10,
    # "Region-International": 11,
    # "Subarea-Vehicle": 12,
    # "Building-Grounds": 13,
    # "Special": 14,
    # "County-or-District": 15,
    # "Projectile": 16,
    # "Water-Body": 17,
    # "Water": 18,
    # "Shooting": 19,
    # "Individual": 20,
    # "Entertainment": 21,
    # "State-or-Province": 22,
    # "GPE-Cluster": 23,
    # "Sports": 24,
    # "Population-Center": 25,
    # "Religious": 26,
    # "Address": 27,
    # "Nation": 28,
    # "Region-General": 29,
    # "Group": 30,
    # "Government": 31,
    # "Indeterminate": 32,
    # "Air": 33,
    # "Nuclear": 34,
    # "Media": 35,
    # "Educational": 36,
    # "Non-Governmental": 37,
    # "Land": 38,
    
    # using type
    "ORG": 2,
    "LOC": 3,
    "FAC": 4,
    "WEA": 5,
    "GPE": 6,
    "PER": 7,
    "VEH": 8,
}

OBJ_NER_TO_ID = {
    PAD_TOKEN: PAD_ID,
    UNK_TOKEN: UNK_ID,
    # "PERSON": 2,
    # "ORGANIZATION": 3,
    # "DATE": 4,
    # "NUMBER": 5,
    # "TITLE": 6,
    # "COUNTRY": 7,
    # "LOCATION": 8,
    # "CITY": 9,
    # "MISC": 10,
    # "STATE_OR_PROVINCE": 11,
    # "DURATION": 12,
    # "NATIONALITY": 13,
    # "CAUSE_OF_DEATH": 14,
    # "CRIMINAL_CHARGE": 15,
    # "RELIGION": 16,
    # "URL": 17,
    # "IDEOLOGY": 18,
    
    # using subtype
    # "Medical-Science": 2,
    # "Underspecified": 3,
    # "Airport": 4,
    # "Boundary": 5,
    # "Subarea-Facility": 6,
    # "Land-Region-Natural": 7,
    # "Path": 8,
    # "Blunt": 9,
    # "Plant": 10,
    # "Celestial": 11,
    # "Commercial": 12,
    # "Exploding": 13,
    # "Region-International": 14,
    # "Subarea-Vehicle": 15,
    # "Building-Grounds": 16,
    # "Special": 17,
    # "County-or-District": 18,
    # "Projectile": 19,
    # "Chemical": 20,
    # "Continent": 21,
    # "Water-Body": 22,
    # "Water": 23,
    # "Shooting": 24,
    # "Individual": 25,
    # "Entertainment": 26,
    # "State-or-Province": 27,
    # "Sharp": 28,
    # "GPE-Cluster": 29,
    # "Sports": 30,
    # "Population-Center": 31,
    # "Religious": 32,
    # "Address": 33,
    # "Nation": 34,
    # "Region-General": 35,
    # "Government": 36,
    # "Group": 37,
    # "Indeterminate": 38,
    # "Air": 39,
    # "Nuclear": 40,
    # "Media": 41,
    # "Educational": 42,
    # "Non-Governmental": 43,
    # "Biological": 44,
    # "Land": 45,
    
    ## using type
    "ORG": 2,
    "LOC": 3,
    "FAC": 4,
    "WEA": 5,
    "GPE": 6,
    "PER": 7,
    "VEH": 8,
}


NER_TO_ID = {
    PAD_TOKEN: PAD_ID,
    UNK_TOKEN: UNK_ID,
    # "O": 2,
    # "PERSON": 3,
    # "ORGANIZATION": 4,
    # "LOCATION": 5,
    # "DATE": 6,
    # "NUMBER": 7,
    # "MISC": 8,
    # "DURATION": 9,
    # "MONEY": 10,
    # "PERCENT": 11,
    # "ORDINAL": 12,
    # "TIME": 13,
    # "SET": 14,
    "FAC": 2,
    "TIME": 3,
    "EVENT": 4,
    "PERSON": 5,
    "DATE": 6,
    "CARDINAL": 7,
    "PRODUCT": 8,
    "WORK_OF_ART": 9,
    "ORG": 10,
    "ORDINAL": 11,
    "PERCENT": 12,
    "GPE": 13,
    "LOC": 14,
    "MONEY": 15,
    "NORP": 16,
    "LANGUAGE": 17,
    "QUANTITY": 18,
    "LAW": 19,
    "O": 20,
}

POS_TO_ID = {
    PAD_TOKEN: PAD_ID,
    UNK_TOKEN: UNK_ID,
    "NNP": 2,
    "NN": 3,
    "IN": 4,
    "DT": 5,
    ",": 6,
    "JJ": 7,
    "NNS": 8,
    "VBD": 9,
    "CD": 10,
    "CC": 11,
    ".": 12,
    "RB": 13,
    "VBN": 14,
    "PRP": 15,
    "TO": 16,
    "VB": 17,
    "VBG": 18,
    "VBZ": 19,
    "PRP$": 20,
    ":": 21,
    "POS": 22,
    "''": 23,
    "``": 24,
    "-RRB-": 25,
    "-LRB-": 26,
    "VBP": 27,
    "MD": 28,
    "NNPS": 29,
    "WP": 30,
    "WDT": 31,
    "WRB": 32,
    "RP": 33,
    "JJR": 34,
    "JJS": 35,
    "$": 36,
    "FW": 37,
    "RBR": 38,
    "SYM": 39,
    "EX": 40,
    "RBS": 41,
    "WP$": 42,
    "PDT": 43,
    "LS": 44,
    "UH": 45,
    "#": 46,
}

LABEL_TO_ID = {
    # "no_relation": 0,
    # "per:title": 1,
    # "org:top_members/employees": 2,
    # "per:employee_of": 3,
    # "org:alternate_names": 4,
    # "org:country_of_headquarters": 5,
    # "per:countries_of_residence": 6,
    # "org:city_of_headquarters": 7,
    # "per:cities_of_residence": 8,
    # "per:age": 9,
    # "per:stateorprovinces_of_residence": 10,
    # "per:origin": 11,
    # "org:subsidiaries": 12,
    # "org:parents": 13,
    # "per:spouse": 14,
    # "org:stateorprovince_of_headquarters": 15,
    # "per:children": 16,
    # "per:other_family": 17,
    # "per:alternate_names": 18,
    # "org:members": 19,
    # "per:siblings": 20,
    # "per:schools_attended": 21,
    # "per:parents": 22,
    # "per:date_of_death": 23,
    # "org:member_of": 24,
    # "org:founded_by": 25,
    # "org:website": 26,
    # "per:cause_of_death": 27,
    # "org:political/religious_affiliation": 28,
    # "org:founded": 29,
    # "per:city_of_death": 30,
    # "org:shareholders": 31,
    # "org:number_of_employees/members": 32,
    # "per:date_of_birth": 33,
    # "per:city_of_birth": 34,
    # "per:charges": 35,
    # "per:stateorprovince_of_death": 36,
    # "per:religion": 37,
    # "per:stateorprovince_of_birth": 38,
    # "per:country_of_birth": 39,
    # "org:dissolved": 40,
    # "per:country_of_death": 41,

    ## using subtype
    # "no_relation": 0,
    # "Located": 1,
    # "Geographical": 2,
    # "Business": 3,
    # "Membership": 4,
    # "Sports-Affiliation": 5,
    # "Student-Alum": 6,
    # "Subsidiary": 7,
    # "User-Owner-Inventor-Manufacturer": 8,
    # "Lasting-Personal": 9,
    # "Ownership": 10,
    # "Investor-Shareholder": 11,
    # "Founder": 12,
    # "Org-Location": 13,
    # "Artifact": 14,
    # "Citizen-Resident-Religion-Ethnicity": 15,
    # "Near": 16,
    # "Employment": 17,
    # "Family": 18,
    
    # using type
    "no_relation": 0,
    "PART-WHOLE(e1,e2)": 1,
    "PART-WHOLE(e2,e1)": 2,
    "PER-SOC(e1,e2)": 3,
    "PER-SOC(e2,e1)": 4,
    "PHYS(e1,e2)": 5,
    "PHYS(e2,e1)": 6,
    "GEN-AFF(e1,e2)": 7,
    "GEN-AFF(e2,e1)": 8,
    "ART(e1,e2)": 9,
    "ART(e2,e1)": 10,
    "ORG-AFF(e1,e2)": 11,
    "ORG-AFF(e2,e1)": 12,
}

INFINITY_NUMBER = 1e12
